version: '3'

services:
  postgresql:
    container_name: caml_bot_db
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_PASSWORD=${PG_PASSWORD}
      - POSTGRESQL_DATABASE=${PG_DATABASE}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres

volumes:
  pgdata:

networks:
  postgres:
    driver: bridge
